name: Minimize Source

on:
  push:
    branches: [main]
    paths: ["src/**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install Minimizer
      run: go install github.com/tdewolff/minify/v2/cmd/minify@latest

    - name: Minify Source
      run: |
        rm -rf docs
        minify -r -s -o docs/ src/
        touch docs/.nojekyll

    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898283+github-actions[bot]@users.noreply.github.com"
        git add docs
        git diff --cached --quiet || git commit -m "Build minified site"
        git push
